import { hot } from 'react-hot-loader';
import addStyles from './add-styles';

addStyles();

export const AdvancedToggle = hot(module)(require('./components/AdvancedToggle').default);
export const Avatar = hot(module)(require('./components/Avatar').default);
export const Banner = hot(module)(require('./components/Banner').default);
export const BannerCarousel = hot(module)(require('./components/BannerCarousel').default);
export const BigLoader = hot(module)(require('./components/BigLoader').default);
export const BrowseInput = hot(module)(require('./components/BrowseInput').default);
export const Button = hot(module)(require('./components/Button').default);
export const Card = hot(module)(require('./components/Card').default);
export const Close = hot(module)(require('./components/Close').default);
export const ClippedContent = hot(module)(require('./components/ClippedContent').default);
export const Divider = hot(module)(require('./components/Divider').default);
export const DownloaderItem = hot(module)(require('./components/DownloaderItem').default);
export const DragBar = hot(module)(require('./components/DragBar').default);
export const Drawer = hot(module)(require('./components/Drawer').default);
export const EmptyArea = hot(module)(require('./components/EmptyArea').EmptyArea);
export const FlyDropdown = hot(module)(require('./components/FlyDropdown').default);
export const FlyLargeConfirm = hot(module)(require('./components/FlyLargeConfirm').default);
export const FlyModal = hot(module)(require('./components/FlyModal').default);
export const FlySelect = hot(module)(require('./components/FlySelect').default);
export const FlyTooltip = hot(module)(require('./components/FlyTooltip').default);
export const Header = hot(module)(require('./components/Header').default);
export const ImageCircle = hot(module)(require('./components/ImageCircle').default);
export const InnerPaneSidebar = hot(module)(require('./components/InnerPaneSidebar').InnerPaneSidebar);
export const InnerPaneSidebarHeader = hot(module)(require('./components/InnerPaneSidebar').InnerPaneSidebarHeader);
export const InnerPaneSidebarAddNew = hot(module)(require('./components/InnerPaneSidebar').InnerPaneSidebarAddNew);
export const InnerPaneSidebarContent = hot(module)(require('./components/InnerPaneSidebar').InnerPaneSidebarContent);
export const InnerPaneSidebarContentItem = hot(module)(require('./components/InnerPaneSidebar').InnerPaneSidebarContentItem);
export const InputPasswordToggle = hot(module)(require('./components/InputPasswordToggle').default);
export const InputSearch = hot(module)(require('./components/InputSearch').default);
export const InstallerStepStatus = hot(module)(require('./components/InstallerStepStatus').default);
export const List = hot(module)(require('./components/List').default);
export const LoadingIndicator = hot(module)(require('./components/LoadingIndicator').default);
export const Markdown = hot(module)(require('./components/Markdown').default);
export const Popup = hot(module)(require('./components/Popup').default);
export const ProgressBar = hot(module)(require('./components/ProgressBar').default);
export const RadioBlock = hot(module)(require('./components/RadioBlock').default);
export const SiteInfoInnerPane = hot(module)(require('./components/SiteInfoInnerPane').default);
export const Stepper = hot(module)(require('./components/Stepper').Stepper);
export const Spinner = hot(module)(require('./components/Spinner').default);
export const Step = hot(module)(require('./components/Stepper').Step);
export const Switch = hot(module)(require('./components/Switch').default);
export const TableList = hot(module)(require('./components/TableList').TableList);
export const TableListRow = hot(module)(require('./components/TableList').TableListRow);
export const TableListRepeater = hot(module)(require('./components/TableListRepeater').default);
export const TabNav = hot(module)(require('./components/TabNav').default);
export const TertiaryNav = hot(module)(require('./components/TertiaryNav').TertiaryNav);
export const TertiaryNavItem = hot(module)(require('./components/TertiaryNav').TertiaryNavItem);
export const Truncate = hot(module)(require('./components/Truncate').default);
export const VerticalNav = hot(module)(require('./components/VerticalNav').VerticalNav);
export const VerticalNavItem = hot(module)(require('./components/VerticalNav').VerticalNavItem);
export const WorkspaceSwitcher = hot(module)(require('./components/VerticalNav').WorkspaceSwitcher);
export const WindowsToolbar = hot(module)(require('./components/WindowsToolbar').default);
